### ISSUE TITLE
Unable to push repository to github

### ISSUE THREAD

**Issue by su6a12** [clnhll/guidetobasejumps#3]
I'm encountering an issue when trying to push my repository to github. Looks like the repo might exceed the size limit that github set.  Is there a workaround?

...
Counting objects: 109, done.
Delta compression using up to 8 threads.
error: pack-objects died of signal 9
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
fatal: write error: Bad file descriptor

**Comment by m66n** [comment]
Did you add the `data` dir to `.gitignore`? It's not in the waypoint directions, but that folder is huge. My `.gitignore` looks like:

```
node_modules
public
.tmp
.idea
client/bower_components
data
dist
/server/config/local.env.js
npm-debug.log
```

**Comment by su6a12** [comment]
@m66n Thank you!  Worked like a charm!
